const games = [
    { name: "Snowball.io", image: "image/snow.png", description: "Battle", link: "snow.html", category: "Battle,Action" },
    { name: "Slope", image: "image/slope.png", description: "Endless Runner", link: "slope.html", category: "Arcade,Action" },
    { name: "Paper.io 2", image: "image/paper.png", description: "Battle", link: "paper.html", category: "Battle,Action" },
    { name: "SNOWRIDER 3D", image: "image/snowrider.png", description: "Endless Runner", link: "snowrider.html", category: "Action" },
    { name: "2048", image: "image/2048.png", description: "Puzzle", link: "2048.html", category: "Puzzle" },
    { name: "2048Multitask", image: "image/2048multi.png", description: "Puzzle", link: "2048multi.html", category: "Puzzle" },
    { name: "1", image: "image/1.png", description: "Puzzle", link: "1.html", category: "Puzzle" },
    { name: "9007199254740992", image: "image/9007199254740992.png", description: "Puzzle", link: "9007199254740992.html", category: "Puzzle" },
    { name: "Flappy2048", image: "image/flappy2048.png", description: "Puzzle", link: "flappy2048.html", category: "Puzzle" },
    { name: "Age Of War", image: "image/aow.png", description: "Battle", link: "aow.html", category: "Arcade,Battle" },
    { name: "Age Of War 2", image: "image/aow2.png", description: "Battle", link: "aow2.html", category: "Arcade,Battle" },
    { name: "Happy Wheels", image: "image/hw.png", description: "Chaos", link: "hw.html", category: "Action" },
    { name: "Minecraft 1.8.8", image: "image/1.8.8.png", description: "minecraft", link: "1.8.8.html", category: "Action,Arcade" },
    { name: "Minecraft 1.12.2", image: "image/1.12.2.png", description: "minecraft", link: "1.12.2.html", category: "Action,Arcade" },
    { name: "Bloxorz", image: "image/bloxorz.png", description: "Use brain", link: "bloxorz.html", category: "Arcade,Puzzle" },
    { name: "Portal", image: "image/portal.png", description: "Use brain", link: "portal.html", category: "Arcade,Puzzle" },
    { name: "Super Mario 64", image: "image/mario64.png", description: "Action!", link: "mario64.html", category: "Action" },
    { name: "dino", image: "image/dino.png", description: "minigame", link: "dino.html", category: "Action,Arcade" },
    { name: "Cookie Clicker", image: "image/cookie.png", description: "Chaos", link: "cookieclicker-gh-pages/index.html", category: "Action,Arcade" },
    { name: "FreeTubeX Local", image: "image/free.png", description: "Tool", link: "freetubex_local.html", category: "Other" },
    { name: "Geometry Dash", image: "image/geodash.png", description: "Rhythm", link: "geodash.html", category: "Rhythm" },
    { name: "Geometry Dash Meltdown", image: "image/meltdown.png", description: "Rhythm", link: "meltdown.html", category: "Rhythm" },
    { name: "Geometry Dash Subzero", image: "image/subzero.png", description: "Rhythm", link: "subzero.html", category: "Rhythm" },
    { name: "SUPER MARIO BROS", image: "image/mario.png", description: "Really?", link: "mario.html", category: "Action,Arcade" },
    { name: "n-gon", image: "image/n-gon.png", description: "GG!", link: "main/n-gon/index.html", category: "Action" },
];
